import type { Metadata } from "next";
import { Rubik, Kalam, Qwitcher_Grypen } from "next/font/google";
import "./globals.css";
import VerticalNav from './_components/RightVerticalNav'; // New import
import { ThemeProvider } from './_utils/ThemeProvider'; // New Import


const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });
const kalam = Kalam({
  subsets: ["latin"], variable: "--font-kalam",
  weight: "300"
});
const qwitcherGrypen = Qwitcher_Grypen({
  subsets: ["latin"], variable: "--font-qwitcher",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning
        className={`${rubik.variable} ${kalam.variable} ${qwitcherGrypen.variable}`}
      >
        <ThemeProvider>
          <VerticalNav />
          <main className="">

            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
